const data = {
  products: [
    {
      name: 'Test 1',
      slug: 'test-1',
      category: 'Category 1',
      price: 150,
      image: '/images/test-1.jpg',
      stock: 10,
      brand: 'Nike',
      rating: 4.5,
      reviewCount: 10,
      description: 'test-1',
    },
    {
      name: 'Test 2',
      slug: 'test-2',
      category: 'Category 1',
      price: 160,
      image: '/images/test-2.jpg',
      stock: 10,
      brand: 'Nike',
      rating: 4.8,
      reviewCount: 10,
      description: 'test-2',
    },
    {
      name: 'Test 3',
      slug: 'test-3',
      category: 'Category 1',
      price: 160,
      image: '/images/test-3.jpg',
      stock: 10,
      brand: 'Nike',
      rating: 4.8,
      reviewCount: 10,
      description: 'test-3',
    },
    {
      name: 'Test 4',
      slug: 'test-4',
      category: 'Category 1',
      price: 160,
      image: '/images/test-4.jpg',
      stock: 10,
      brand: 'Nike',
      rating: 4.8,
      reviewCount: 10,
      description: 'test-4',
    },
    {
      name: 'Test 5',
      slug: 'test-5',
      category: 'Category 5',
      price: 160,
      image: '/images/test-5.jpg',
      stock: 10,
      brand: 'Nike',
      rating: 4.8,
      reviewCount: 10,
      description: 'test-5',
    },
  ],
};
export default data;
